# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: route_guide.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'route_guide.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import person_pb2 as person__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11route_guide.proto\x1a\x0cperson.proto\"\x14\n\x04Name\x12\x0c\n\x04name\x18\x01 \x01(\t2N\n\nRouteGuide\x12\x1d\n\tGetPerson\x12\x05.Name\x1a\x07.Person\"\x00\x12!\n\tGetPeople\x12\x05.Name\x1a\x07.Person\"\x00(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'route_guide_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NAME']._serialized_start=35
  _globals['_NAME']._serialized_end=55
  _globals['_ROUTEGUIDE']._serialized_start=57
  _globals['_ROUTEGUIDE']._serialized_end=135
# @@protoc_insertion_point(module_scope)
